# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-03 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('SendingCost', models.IntegerField(blank=True, null=True)),
                ('TransporterResponse', models.BooleanField(default=False)),
                ('CourierNumber', models.IntegerField(blank=True, null=True)),
                ('ParcelCost', models.IntegerField()),
                ('ParcelStatus', models.CharField(choices=[('searching', 'searching transporter'), ('waiting', ' waiting courier'), ('ontransit', 'on transit'), ('received', 'received'), ('delivered', 'delivered')], max_length=20)),
                ('DeliveredSender', models.BooleanField(default=False)),
                ('DeliveredTransporter', models.BooleanField(default=False)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone', models.IntegerField()),
                ('date', models.DateField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels_sender', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels_transporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parcels',
            },
        ),
    ]
