# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcels',
            options={'verbose_name_plural': 'Parcels'},
        ),
    ]
