# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelsapp', '0002_auto_20170822_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcels',
            name='parcelstatus',
            field=models.CharField(blank=True, choices=[('ontransit', 'ontransit'), ('delivered', 'delivered')], max_length=20, null=True),
        ),
    ]
