# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelsapp', '0003_parcels_parcelstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='parcelstatus',
            field=models.CharField(choices=[('ontransit', 'ontransit'), ('delivered', 'delivered')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
