# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelsapp', '0004_auto_20170822_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcels',
            name='parcelstatus',
        ),
        migrations.AddField(
            model_name='parcels',
            name='CourierNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcels',
            name='DeliveredSender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcels',
            name='DeliveredTransporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcels',
            name='ParcelStatus',
            field=models.CharField(choices=[('searching', 'transporter'), ('waiting', 'courier'), ('ontransit', 'ontransit'), ('received', 'received')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcels',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcels_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcels',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels_transporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='SendingCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
