# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelsapp', '0005_auto_20170824_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcels',
            name='TransporterResponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='ParcelStatus',
            field=models.CharField(choices=[('searching', 'searching transporter'), ('waiting', ' waiting courier'), ('ontransit', 'on transit'), ('received', 'received')], max_length=20),
        ),
    ]
