# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelsapp', '0006_auto_20170831_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='ParcelStatus',
            field=models.CharField(choices=[('searching', 'searching transporter'), ('waiting', ' waiting courier'), ('ontransit', 'on transit'), ('received', 'received'), ('delivered', 'delivered')], max_length=20),
        ),
    ]
