# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-11 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsmodel',
            options={'verbose_name_plural': 'Jobs'},
        ),
    ]
