# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usermanagerapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('constituency', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('IdNo', models.CharField(blank=True, max_length=8, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=usermanagerapp.models.get_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
