# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='TransporterAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='TransporterRequest',
            field=models.BooleanField(default=False),
        ),
    ]
