# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerapp', '0002_auto_20170904_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
