# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerapp', '0003_profile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
    ]
