# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerapp', '0004_auto_20180501_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='IdNo',
            new_name='Id_No',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='TransporterAccepted',
            new_name='Transporter_Accepted',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='TransporterRequest',
            new_name='Transporter_Request',
        ),
    ]
