# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerapp', '0007_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=1234, max_length=6),
            preserve_default=False,
        ),
    ]
