# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerapp', '0008_profile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
    ]
